### ISSUE TITLE
update gbcc

### ISSUE THREAD

**Issue by soundsnow** [philj56/gbcc-android#20]
gbcc-universal-debug.apk
App not installed as package conflicts wit sn existing package

**Comment by philj56** [comment]
Yep, this is a feature of Android. If you're changing between the release / debug versions of GBCC, you have to uninstall it first due to app signing differences. It might be possible to make it so that you can have both installed simultaneously though, which I would find useful as well - I'll look into it.

**Comment by philj56** [comment]
I've fixed this in e818bc1de96742bc530a7662431d2a0b23355343, you can now have the debug and release versions installed simultaneously.
